# -*- coding: utf-8 -*-
"""Car manufacturing Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12z1zriY44jxTyRMPbNn_gRWBQw1UbfO3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("USA_cars_datasets.csv")

df.head()

del df['Unnamed: 0'], df['vin'], df['lot'], df['condition']

df.head()

"""#**1. What are top 5 car brands in terms of number of cars?**"""

#creating a array to store cars of a particular brand according to
#their frequencies
cars = []

for brand in df['brand'].unique():
  cars.append([brand,len(df[df['brand']== brand])])

#creating a dataframe from obtained array
cars_df = pd.DataFrame(cars,columns = ['brand','freq'])

# sorting the data inside dataframe
cars_df = cars_df.sort_values(by = 'freq', ascending = False)

ans_1 = cars_df.head()

print(ans_1)
ans_1.plot.bar(x = 'brand', y='freq', figsize = (5,4))

#plot for all car brands with respect to their frequency
cars_df.plot.bar(x = 'brand',y='freq',figsize = (10,5))

"""#**2. What is the observed car industry trend according to given data?**"""

#creating a array to store trend of a particular brand according to years.
trend = []

for year in df['year'].unique():
  trend.append([year,len(df[df['year']==year])])

#creating a dataframe from obtained array
trend_df = pd.DataFrame(trend,columns = ['year','freq'])

# sorting the data inside dataframe
trend_df = trend_df.sort_values(by = 'year', ascending = True)

#plot for ongoing trend according to given data
trend_df.plot.line(x = 'year', y = 'freq', figsize=(10,5))

"""#**3.Which color is most popular in car industry?**"""

#creating a array to store most popular car with respect to their frequencies.
colour =[]

for color in  df['color'].unique():
  colour.append([color,len(df[df['color']==color])])

#creating a dataframe using obtained array
color_df = pd.DataFrame(colour,columns = ['color','freq'])

#sorting the data
color_df = color_df.sort_values(by='freq', ascending = False)

ans_3 = color_df.head()

print(ans_3)
#plot for most popular colour
color_df.plot.bar(x = 'color',y = 'freq',figsize=(10,5))

"""#**4. Which car brand has maximum average price?**"""

# creating a dataframe such that it stores data in form of mean
average_df = df.groupby('brand').mean()

# filtering out  mean data according to cost
average_df = average_df['price']

#sorting the data
average_df = average_df.sort_values(ascending = False)

ans_4 = average_df.head()

print(ans_4)
# ploting the curve to know average prices for each brand
average_df.plot.bar(figsize = (10,5))

"""#**5. Which state on an average has most expensive cars?**"""

# creating a dataframe to store data with respect to each state
cost_df = df.groupby('state').mean()

# modifying the dataframe according to the cost of cars
cost_df = cost_df['price']

# sorting the data
cost_df = cost_df.sort_values(ascending = False)

ans_5 = cost_df.head()

print(ans_5)
#plotting the graph to visualize which state has most expensive cars
cost_df.plot.bar(figsize = (10,5))

"""#**6. Which year has maximum average price of cars?**"""

# creating a dataframe to store data with respect to mean cost according to 
# particular year
year_df = df.groupby('year').mean()

# filtering the data with prices.
year_df = year_df['price']

#sorting the data
year_df = year_df.sort_values(ascending = False)

ans_6 = year_df.head()

print(ans_6)
#plotting the curve to find which year has maximum average cost of cars
year_df.plot.bar(figsize = (10,5))