# -*- coding: utf-8 -*-
"""Olympics Data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0Pw0Xjcg0SpVMPfePOK3Unypt5NZ9LM
"""

import pandas as pd
import numpy as np

df = pd.read_csv("summer.csv")

df

"""#**1. In how many cities Summer Olympics is held so far?**"""

ans_1 = len(df['City'].unique())
print(ans_1)

"""#**2. Which sport is having most number of Gold Medals so far? (Top 5)**"""

# narrowing dataframe to gold medals
gold_df = df[df['Medal'] =="Gold"]

# grouping gold medals with respective to sports
gold_df = gold_df.groupby('Sport')

#counting gold medals for each sports
gold_df = gold_df.count()['Medal']

#sorting in non-increasing order
gold_df = gold_df.sort_values(ascending = False)

#filtering out top 5 sports having most gold medals.
ans_2 = gold_df.head()

print(ans_2)

# A bar graph showing top 5 sports having most gold medals.
ans_2.plot.bar(figsize = (5,4))

"""#**3. Which sport is having most number of medals so far? (Top 5)**"""

# grouping medals with respective to sports
medal_df = df.groupby('Sport')

#counting medals for each sports
medal_df = medal_df.count()['Medal']

#sorting in non-increasing order
medal_df = medal_df.sort_values(ascending = False)

#filtering out top 5 sports having most medals.
ans_3 = medal_df.head()

print(ans_3)

# A bar graph showing top 5 sports having most medals.
ans_3.plot.bar(figsize = (5,4))

"""#**4. Which player has won most number of medals? (Top 5)**"""

# grouping medals with respective to athlete
athlete_df = df.groupby('Athlete')

#counting medals for each athlete
athlete_df = athlete_df.count()['Medal']

#sorting in non-increasing order
athlete_df = athlete_df.sort_values(ascending = False)

#filtering out top 5 athlete having most medals.
ans_4 = athlete_df.head()

print(ans_4)

# A bar graph showing top 5 athlete having most medals.
ans_4.plot.bar(figsize = (4,3))

"""#**5. Which player has won most number of Gold Medals of medals? (Top 5)**"""

# narrowing dataframe to gold medals
athlete_gold_df = df[df['Medal'] =="Gold"]

# grouping gold medals with respective to athlete
athlete_gold_df = athlete_gold_df.groupby('Athlete')

#counting gold medals for each athlete
athlete_gold_df = athlete_gold_df.count()['Medal']

#sorting in non-increasing order
athlete_gold_df = athlete_gold_df.sort_values(ascending = False)

#filtering out top 5 athlete having most gold medals.
ans_5 = athlete_gold_df.head()

print(ans_5)

# A bar graph showing top 5 athlete having most gold medals.
ans_5.plot.bar(figsize = (5,4))

"""#**6. In which year India won first Gold Medal in Summer Olympics?**"""

#filtering dataframe to only data of india
india_df = df[df['Country']=='IND']

#filtering out data providing information about gold medals and mapping them 
#with respective year of acheivement.
india_df = india_df[india_df['Medal']=='Gold']['Year']

ans_6 = india_df.min()
print(ans_6)

"""#**7. Which event is more popular in terms of numbers of players? (Top 5)**"""

#grouping dataframe according to events
event_df = df.groupby('Event')

#counting number of athlete for each event
event_df = event_df.count()['Athlete']

#sorting the data
event_df = event_df.sort_values(ascending = False)

#filtering out top 5 events
ans_7 = event_df.head()

print(ans_7)

# A bar graph showing top 5 events
ans_7.plot.bar(figsize = (5,4))

"""#**8. Which sport is having most female Gold Medalists? (Top 5)**"""

# creating the female dataframe from given dataframe
female_df = df[df['Gender']=='Women']

# modifying dataframe with respect to gold medals acheived by womens
female_df = female_df[female_df['Medal']=='Gold']

#grouping according to sports
female_df = female_df.groupby('Sport')

#counting with respect to medals acheived
female_df = female_df.count()['Medal']

# sorting the data
female_df = female_df.sort_values(ascending = False)

# filtering top 5 female athletes who won gold medals
ans_8 = female_df.head()

print(ans_8)
ans_8.plot.bar(figsize= (5,4))

